'use client'

import React, { type FC } from 'react'

import { Home } from 'lucide-react'
import Link from 'next/link'

import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@/components/ui/breadcrumb'
import { cn } from '@/lib/utils'

import type { BreadcrumbItem as BreadcrumbItemType } from '@/features/blog/types/breadcrumb'

type PostBreadcrumbProps = {
  breadcrumbItems: BreadcrumbItemType[]
  className?: string
  separatorClassName?: string
  pageClassName?: string
  linkClassName?: string
}

/**
 * Reusable breadcrumb component for post pages
 * Accepts breadcrumbItems generated by generateBreadcrumb utility
 * Supports custom styling for different post styles
 */
export const PostBreadcrumb: FC<PostBreadcrumbProps> = ({
  breadcrumbItems,
  className,
  separatorClassName,
  pageClassName,
  linkClassName,
}) => {
  if (!breadcrumbItems || breadcrumbItems.length === 0) {
    return null
  }

  return (
    <div className="-mx-4 w-full overflow-x-auto px-4 sm:mx-0 sm:px-0">
      <Breadcrumb className={className}>
        <BreadcrumbList className="min-w-max flex-nowrap">
          {breadcrumbItems.map((item, index) => (
            <React.Fragment key={`breadcrumb-${index}`}>
              <BreadcrumbItem className="flex-shrink-0">
                {item.isCurrent ? (
                  <BreadcrumbPage
                    className={cn('max-w-[150px] truncate sm:max-w-none', pageClassName)}
                  >
                    {item.label}
                  </BreadcrumbPage>
                ) : (
                  <BreadcrumbLink href={item.url || '/'} asChild>
                    <Link
                      href={item.url || '/'}
                      className={cn(
                        'inline-flex max-w-[120px] items-center gap-1 truncate sm:max-w-none',
                        linkClassName,
                      )}
                    >
                      {item.isHome ? <Home className="h-4 w-4 flex-shrink-0" /> : item.label}
                    </Link>
                  </BreadcrumbLink>
                )}
              </BreadcrumbItem>
              {index < breadcrumbItems.length - 1 && (
                <BreadcrumbSeparator className={cn('flex-shrink-0', separatorClassName)}>
                  <span className="mx-1.5">/</span>
                </BreadcrumbSeparator>
              )}
            </React.Fragment>
          ))}
        </BreadcrumbList>
      </Breadcrumb>
    </div>
  )
}
